name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        registry: ['https://registry.npmjs.org', 'https://npm.pkg.github.com']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: ${{ matrix.registry }}
      - run: npm ci
      - name: Publish to npm registry
        if: matrix.registry == 'https://registry.npmjs.org'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to GitHub Packages
        if: matrix.registry == 'https://npm.pkg.github.com'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
